### ISSUE TITLE
Write an initial technical report

### ISSUE THREAD

**Issue by budang** [cs373gc-fall-2016/SouthernWholesomeEducation#10]
- Write an initial technical report using the GitHub Wiki.
- The audience comprises other software developers, as opposed to users.
- For this phase it must be at least 2500 words.
- Document the RESTful API and the models well.
- Format the report clearly, attractively, and consistently, using good headers, figures, and grammar.
- Quality of the technical report;
  - 2,500 words, use cases, models, DB
  - good sections, multiple pages, good headers, figures, and grammar

**Comment by jymin94** [comment]
Reached 2500 words!
